--[[                                                                           ]]--
--[[  Generated by FAF Map Editor                                              ]]--
--[[                                                                           ]]--
--[[                                                                           ]]--
--[[  Scenario                                                                 ]]--
--[[                                                                           ]]--
Scenario = {
    next_area_id = '0',
    --[[                                                                           ]]--
    --[[  Props                                                                    ]]--
    --[[                                                                           ]]--
    Props = {
    },
    --[[                                                                           ]]--
    --[[  Areas                                                                    ]]--
    --[[                                                                           ]]--
    Areas = {
        ['AREA_1'] = {
            ['rectangle'] = RECTANGLE( 0, 128, 512, 384 ),
        },
    },
    --[[                                                                           ]]--
    --[[  Markers                                                                  ]]--
    --[[                                                                           ]]--
    MasterChain = {
        ['_MASTERCHAIN_'] = {
            Markers = {
                ['Hydrocarbon 03'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 360.5, 35.00214, 174.5 ),
                },
                ['LW_L1_Cap1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 172.5, 35.00214, 255.5 ),
                },
                ['LW_L2_Cap1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 172.5, 35.00214, 174.5 ),
                },
                ['LW_L2_Spawn_B'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 360.5, 35.00214, 174.5 ),
                },
                ['Hydrocarbon 01'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 360.5, 35.00214, 255.5 ),
                },
                ['LW_L1_Spawn_A'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 151.5, 35.00214, 255.5 ),
                },
                ['ARMY_5'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 81.5, 35.00214, 338.5 ),
                },
                ['LW_L1_Cap5'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 289.5, 35.00214, 255.5 ),
                },
                ['ARMY_2'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 432.5, 35.00214, 255.5 ),
                },
                ['LW_L2_Cap5'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 289.5, 35.00214, 174.5 ),
                },
                ['LW_L1_Cap3'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 222.5, 35.00214, 255.5 ),
                },
                ['LW_NoBuild1_B'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 362.5, 54.58157, 128.5 ),
                },
                ['LW_L3_Cap7'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 339.5, 35.00214, 339.5 ),
                },
                ['LW_L3_Cap2'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 198.5, 35.00214, 339.5 ),
                },
                ['Hydrocarbon 00'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 151.5, 35.00214, 255.5 ),
                },
                ['ARMY_3'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 81.5, 35.00214, 173.5 ),
                },
                ['LW_L2_Core_B'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 458.5, 35.00214, 175.5 ),
                },
                ['LW_L3_Cap6'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 313.5, 35.00214, 339.5 ),
                },
                ['LW_L3_Cap4+'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 256.5, 35.00214, 339.5 ),
                },
                ['LW_L3_Cap5'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 289.5, 35.00214, 339.5 ),
                },
                ['LW_L2_Cap6'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 313.5, 35.00214, 174.5 ),
                },
                ['LW_L3_Cap3'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 222.5, 35.00214, 339.5 ),
                },
                ['LW_L3_Cap1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 172.5, 35.00214, 339.5 ),
                },
                ['ARMY_4'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 432.5, 35.00214, 173.5 ),
                },
                ['LW_L1_Spawn_B'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 360.5, 35.00214, 255.5 ),
                },
                ['Hydrocarbon 04'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 151.5, 35.00214, 339.5 ),
                },
                ['LW_L2_Cap7'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 339.5, 35.00214, 174.5 ),
                },
                ['LW_L2_Cap4+'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 256.5, 35.00214, 174.5 ),
                },
                ['LW_L2_Cap3'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 222.5, 35.00214, 174.5 ),
                },
                ['LW_L2_Cap2'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 198.5, 35.00214, 174.5 ),
                },
                ['ARMY_6'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 432.5, 35.00214, 338.5 ),
                },
                ['LW_L3_Core_B'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 458.5, 35.00214, 340.5 ),
                },
                ['ARMY_1'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 81.5, 35.00214, 255.5 ),
                },
                ['Hydrocarbon 05'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 360.5, 35.00214, 339.5 ),
                },
                ['LW_L1_Cap6'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 313.5, 35.00214, 255.5 ),
                },
                ['LW_L1_Core_A'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 55.5, 35.00214, 255.5 ),
                },
                ['LW_L1_Cap2'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 198.5, 35.00214, 255.5 ),
                },
                ['LW_L1_Cap7'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 339.5, 35.00214, 255.5 ),
                },
                ['LW_L3_Core_A'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 55.5, 35.00214, 339.5 ),
                },
                ['Hydrocarbon 02'] = {
                    ['size'] = FLOAT( 3.000000 ),
                    ['resource'] = BOOLEAN( true ),
                    ['amount'] = FLOAT( 100.000000 ),
                    ['color'] = STRING( 'ff008000' ),
                    ['type'] = STRING( 'Hydrocarbon' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 151.5, 35.00214, 174.5 ),
                },
                ['LW_L2_Spawn_A'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 151.5, 35.00214, 174.5 ),
                },
                ['LW_L3_Spawn_B'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 360.5, 35.00214, 339.5 ),
                },
                ['LW_L2_Core_A'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 55.5, 35.00214, 174.5 ),
                },
                ['LW_L1_Core_B'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 458.5, 35.00214, 256.5 ),
                },
                ['LW_L3_Spawn_A'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 151.5, 35.00214, 339.5 ),
                },
                ['LW_NoBuild1_A'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 151.5, 46.77238, 384.5 ),
                },
                ['LW_L1_Cap4+'] = {
                    ['color'] = STRING( 'ff800080' ),
                    ['type'] = STRING( 'Blank Marker' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_Blank_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 0, 0 ),
                    ['position'] = VECTOR3( 256.5, 35.00214, 255.5 ),
                },
            },
        },
    },
    Chains = {
    },
    next_queue_id = '0',
    --[[                                                                           ]]--
    --[[  Orders                                                                   ]]--
    --[[                                                                           ]]--
    Orders = {
    },
    next_platoon_id = '0',
    --[[                                                                           ]]--
    --[[  Platoons                                                                 ]]--
    --[[                                                                           ]]--
    Platoons = {
    },
    next_army_id = '0',
    next_group_id = '0',
    next_unit_id = '0',
    --[[                                                                           ]]--
    --[[  Armies                                                                   ]]--
    --[[                                                                           ]]--
    Armies = {
        --[[                                                                           ]]--
        --[[  ARMY_1                                                                   ]]--
        --[[                                                                           ]]--
        ['ARMY_1'] = 
        {
            personality = '',
            plans = '',
            color = 1,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['ARMY_3'] = 'Ally',
                ['ARMY_2'] = 'Enemy',
                ['ARMY_4'] = 'Enemy',
                ['ARMY_5'] = 'Ally',
                ['ARMY_6'] = 'Enemy',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  ARMY_2                                                                   ]]--
        --[[                                                                           ]]--
        ['ARMY_2'] = 
        {
            personality = '',
            plans = '',
            color = 2,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['ARMY_3'] = 'Enemy',
                ['ARMY_1'] = 'Enemy',
                ['ARMY_4'] = 'Ally',
                ['ARMY_5'] = 'Enemy',
                ['ARMY_6'] = 'Ally',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  ARMY_3                                                                   ]]--
        --[[                                                                           ]]--
        ['ARMY_3'] = 
        {
            personality = '',
            plans = '',
            color = 3,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['ARMY_4'] = 'Enemy',
                ['ARMY_1'] = 'Ally',
                ['ARMY_2'] = 'Enemy',
                ['ARMY_5'] = 'Ally',
                ['ARMY_6'] = 'Enemy',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  ARMY_4                                                                   ]]--
        --[[                                                                           ]]--
        ['ARMY_4'] = 
        {
            personality = '',
            plans = '',
            color = 4,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['ARMY_3'] = 'Enemy',
                ['ARMY_1'] = 'Enemy',
                ['ARMY_2'] = 'Ally',
                ['ARMY_5'] = 'Enemy',
                ['ARMY_6'] = 'Ally',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  ARMY_5                                                                   ]]--
        --[[                                                                           ]]--
        ['ARMY_5'] = 
        {
            personality = '',
            plans = '',
            color = 5,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['ARMY_3'] = 'Ally',
                ['ARMY_1'] = 'Ally',
                ['ARMY_2'] = 'Enemy',
                ['ARMY_4'] = 'Enemy',
                ['ARMY_6'] = 'Enemy',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  ARMY_6                                                                   ]]--
        --[[                                                                           ]]--
        ['ARMY_6'] = 
        {
            personality = '',
            plans = '',
            color = 6,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
                ['ARMY_4'] = 'Ally',
                ['ARMY_2'] = 'Ally',
                ['ARMY_1'] = 'Enemy',
                ['ARMY_5'] = 'Enemy',
                ['ARMY_3'] = 'Enemy',
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['INITIAL'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  ARMY_WAVE_1                                                              ]]--
        --[[                                                                           ]]--
        ['ARMY_WAVE_1'] = 
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['LANE_TOWERS'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['A1T_A1_TOWERS'] = GROUP {
                                prefix = 'A1T',
                                orders = '',
                                platoon = '',
                                Units = {
                                    ['UNIT_9'] = {
                                        type = 'ueb2101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 202.5, 35.00214, 265.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_0'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 119.5, 35.00214, 261.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_2'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 119.5, 35.00214, 250.5 },
                                        Orientation = { 0, -3.141593, 0 },
                                    },
                                    ['UNIT_4'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 160.5, 35.00214, 276.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_13'] = {
                                        type = 'ueb2101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 240.5, 35.00214, 255.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_10'] = {
                                        type = 'ueb2101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 202.5, 35.00214, 246.5 },
                                        Orientation = { 0, -3.141593, 0 },
                                    },
                                    ['UNIT_6'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 160.5, 35.00214, 235.5 },
                                        Orientation = { 0, -3.141593, 0 },
                                    },
                                    ['UNIT_42'] = {
                                        type = 'xeb2306',
                                        orders = '',
                                        platoon = '',
                                        Position = { 116.5, 35.00214, 255.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_50'] = {
                                        type = 'ueb2304',
                                        orders = '',
                                        platoon = '',
                                        Position = { 111.5, 35.00214, 255.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  ARMY_WAVE_2                                                              ]]--
        --[[                                                                           ]]--
        ['ARMY_WAVE_2'] = 
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['LANE_TOWERS'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['A2T_A2_TOWERS'] = GROUP {
                                prefix = 'A2T',
                                orders = '',
                                platoon = '',
                                Units = {
                                    ['UNIT_1'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 392.5, 35.00214, 261.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_3'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 392.5, 35.00214, 250.5 },
                                        Orientation = { 0, -3.141593, 0 },
                                    },
                                    ['UNIT_5'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 351.5, 35.00214, 276.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_12'] = {
                                        type = 'ueb2101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 271.5, 35.00214, 255.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_8'] = {
                                        type = 'ueb2101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 309.5, 35.00214, 265.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_7'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 351.5, 35.00214, 235.5 },
                                        Orientation = { 0, -3.141593, 0 },
                                    },
                                    ['UNIT_11'] = {
                                        type = 'ueb2101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 309.5, 35.00214, 246.5 },
                                        Orientation = { 0, -3.141593, 0 },
                                    },
                                    ['UNIT_43'] = {
                                        type = 'xeb2306',
                                        orders = '',
                                        platoon = '',
                                        Position = { 395.5, 35.00214, 255.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_51'] = {
                                        type = 'ueb2304',
                                        orders = '',
                                        platoon = '',
                                        Position = { 400.5, 35.00214, 255.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  ARMY_WAVE_3                                                              ]]--
        --[[                                                                           ]]--
        ['ARMY_WAVE_3'] = 
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['LANE_TOWERS'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['A3T_A3_TOWERS'] = GROUP {
                                prefix = 'A3T',
                                orders = '',
                                platoon = '',
                                Units = {
                                    ['UNIT_22'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 119.5, 35.00214, 180.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_26'] = {
                                        type = 'ueb2101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 202.5, 35.00214, 165.5 },
                                        Orientation = { 0, -3.141593, 0 },
                                    },
                                    ['UNIT_25'] = {
                                        type = 'ueb2101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 240.5, 35.00214, 174.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_23'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 119.5, 35.00214, 169.5 },
                                        Orientation = { 0, -3.141593, 0 },
                                    },
                                    ['UNIT_21'] = {
                                        type = 'ueb2101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 202.5, 35.00214, 184.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_27'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 160.5, 35.00214, 154.5 },
                                        Orientation = { 0, -3.141593, 0 },
                                    },
                                    ['UNIT_24'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 160.5, 35.00214, 195.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_44'] = {
                                        type = 'xeb2306',
                                        orders = '',
                                        platoon = '',
                                        Position = { 116.5, 35.00214, 174.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_52'] = {
                                        type = 'ueb2304',
                                        orders = '',
                                        platoon = '',
                                        Position = { 111.5, 35.00214, 174.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  ARMY_WAVE_4                                                              ]]--
        --[[                                                                           ]]--
        ['ARMY_WAVE_4'] = 
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['LANE_TOWERS'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['A4T_A4_TOWERS'] = GROUP {
                                prefix = 'A4T',
                                orders = '',
                                platoon = '',
                                Units = {
                                    ['UNIT_19'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 351.5, 35.00214, 154.5 },
                                        Orientation = { 0, -3.141593, 0 },
                                    },
                                    ['UNIT_20'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 351.5, 35.00214, 195.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_16'] = {
                                        type = 'ueb2101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 309.5, 35.00214, 165.5 },
                                        Orientation = { 0, -3.141593, 0 },
                                    },
                                    ['UNIT_18'] = {
                                        type = 'ueb2101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 309.5, 35.00214, 184.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_17'] = {
                                        type = 'ueb2101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 271.5, 35.00214, 174.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_14'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 392.5, 35.00214, 180.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_15'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 392.5, 35.00214, 169.5 },
                                        Orientation = { 0, -3.141593, 0 },
                                    },
                                    ['UNIT_45'] = {
                                        type = 'xeb2306',
                                        orders = '',
                                        platoon = '',
                                        Position = { 395.5, 35.00214, 174.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_53'] = {
                                        type = 'ueb2304',
                                        orders = '',
                                        platoon = '',
                                        Position = { 400.5, 35.00214, 174.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  ARMY_WAVE_5                                                              ]]--
        --[[                                                                           ]]--
        ['ARMY_WAVE_5'] = 
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['LANE_TOWERS'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['A5T_A5_TOWERS'] = GROUP {
                                prefix = 'A5T',
                                orders = '',
                                platoon = '',
                                Units = {
                                    ['UNIT_38'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 119.5, 35.00214, 334.5 },
                                        Orientation = { 0, -3.141593, 0 },
                                    },
                                    ['UNIT_41'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 160.5, 35.00214, 360.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_35'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 119.5, 35.00214, 345.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_37'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 160.5, 35.00214, 319.5 },
                                        Orientation = { 0, -3.141593, 0 },
                                    },
                                    ['UNIT_36'] = {
                                        type = 'ueb2101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 202.5, 35.00214, 330.5 },
                                        Orientation = { 0, -3.141593, 0 },
                                    },
                                    ['UNIT_40'] = {
                                        type = 'ueb2101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 240.5, 35.00214, 339.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_39'] = {
                                        type = 'ueb2101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 202.5, 35.00214, 349.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_46'] = {
                                        type = 'xeb2306',
                                        orders = '',
                                        platoon = '',
                                        Position = { 116.5, 35.00214, 339.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_48'] = {
                                        type = 'ueb2304',
                                        orders = '',
                                        platoon = '',
                                        Position = { 111.5, 35.00214, 339.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
        --[[                                                                           ]]--
        --[[  ARMY_WAVE_6                                                              ]]--
        --[[                                                                           ]]--
        ['ARMY_WAVE_6'] = 
        {
            personality = '',
            plans = '',
            color = 0,
            faction = 0,
            Economy = {
                mass = 0,
                energy = 0,
            },
            Alliances = {
            },
            ['Units'] = GROUP {
                orders = '',
                platoon = '',
                Units = {
                    ['LANE_TOWERS'] = GROUP {
                        orders = '',
                        platoon = '',
                        Units = {
                            ['A6T_A6_TOWERS'] = GROUP {
                                prefix = 'A6T',
                                orders = '',
                                platoon = '',
                                Units = {
                                    ['UNIT_32'] = {
                                        type = 'ueb2101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 271.5, 35.00214, 339.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_28'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 351.5, 35.00214, 319.5 },
                                        Orientation = { 0, -3.141593, 0 },
                                    },
                                    ['UNIT_33'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 392.5, 35.00214, 345.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_34'] = {
                                        type = 'ueb2101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 309.5, 35.00214, 330.5 },
                                        Orientation = { 0, -3.141593, 0 },
                                    },
                                    ['UNIT_31'] = {
                                        type = 'ueb2101',
                                        orders = '',
                                        platoon = '',
                                        Position = { 309.5, 35.00214, 349.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_29'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 351.5, 35.00214, 360.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_30'] = {
                                        type = 'ueb2301',
                                        orders = '',
                                        platoon = '',
                                        Position = { 392.5, 35.00214, 334.5 },
                                        Orientation = { 0, -3.141593, 0 },
                                    },
                                    ['UNIT_47'] = {
                                        type = 'xeb2306',
                                        orders = '',
                                        platoon = '',
                                        Position = { 395.5, 35.00214, 339.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                    ['UNIT_49'] = {
                                        type = 'ueb2304',
                                        orders = '',
                                        platoon = '',
                                        Position = { 400.5, 35.00214, 339.5 },
                                        Orientation = { 0, 0, 0 },
                                    },
                                },
                            },
                        },
                    },
                },
            },
            PlatoonBuilders = {
                next_platoon_builder_id = '1',
                Builders = {
                },
            },
        },
    },
}
