options = 
{
	{ 
		default = 1, 
		label = "Language", 
		help = "Language", 
		key = 'opt_language', 
		pref = 'opt_language', 
		values = { 
			{text = "English", help = "English", key = 1, }, 
			{text = "Francais", help = "French", key = 2, }, 
		}, 
	},
	{ 
		default = 1, 
		label = "All factions", 
		help = "Language", 
		key = 'opt_faction', 
		pref = 'opt_faction', 
		values = { 
			{text = "Yes", help = "yes", key = 1, }, 
			{text = "No", help = "no", key = 2, }, 
		}, 
	},
	{ 
		default = 1, 
		label = "Enemy health", 
		help = "Enemy health", 
		key = 'opt_solidite', 
		pref = 'opt_solidite', 
		values = { 
			{text = "Normal (default)", help = "Normal", key = 1, }, 
			{text = "x2", help = "Harder", key = 2, }, 
			{text = "x3", help = "Kick me", key = 3, }, 
			{text = "x4", help = "Shoot me", key = 4, }, 
			{text = "x5", help = "He's dead, Bone!", key = 5, },
			{text = "x7", help = "He's still dead!", key = 7, },
			{text = "x9", help = "Dead! Dead", key = 9, },
			{text = "x12", help = "He's dead, Bone!", key = 12, },
			{text = "x15", help = "Burn Baby", key = 15, },
			{text = "x19", help = "Burn Baby", key = 19, },
			{text = "x24", help = "I can't believe it", key = 24, },
			{text = "x29", help = "I can't believe it", key = 29, },
			{text = "x35", help = "I can't believe it", key = 35, },
			{text = "x45", help = "Goldlike", key = 45, },
			{text = "x70", help = "Godlike", key = 70, },
			{text = "x100", help = "Right Hand of God", key = 100, },
		}, 
	},
	{ 
		default = 1, 
		label = "Unit multiplier per waves", 
		help = "Unit multiplier per waves", 
		key = 'opt_nombre', 
		pref = 'opt_nombre', 
		values = { 
			{text = "Normal (default)", help = "Kick me", key = 1, }, 
			{text = "x2", help = "Shoot me", key = 2, }, 
			{text = "x3", help = "He's dead, Bone!", key = 3, },
			{text = "x4", help = "He's still dead!", key = 4, },
			{text = "x6", help = "Dead! Dead", key = 6, },
			{text = "x8", help = "He's dead, Bone!", key = 8, },
			{text = "x16", help = "Burn Baby", key = 16, },
			{text = "x24", help = "Godlike", key = 24, },
			{text = "x32", help = "Right Hand of God", key = 32, },
		}, 
	}, 
	{ 
		default = 50, 
		label = "Spread % after a wave has been killed", 
		help = "Spread % after a wave has been killed", 
		key = 'opt_propagation', 
		pref = 'opt_propagation', 
		values = { 
			{text = "50% (default)",help = "", key = 50, }, 
			{text = "10%",help = "", key = 10, }, 
			{text = "20%",help = "", key = 20, }, 
			{text = "30%",help = "", key = 30, }, 
			{text = "40%",help = "", key = 40, }, 
			{text = "50%",help = "", key = 50, }, 
			{text = "60%",help = "", key = 60, }, 
			{text = "70%",help = "", key = 70, }, 
			{text = "80%",help = "", key = 80, }, 
			{text = "90%",help = "", key = 90, }, 
			{text = "100%",help = "", key = 100, }, 
		}, 
	},
	{ 
		default = 1, 
		label = "Types of multiplier for teamplay", 
		help = "C", 
		key = 'opt_multiplicateur', 
		pref = 'opt_multiplicateur', 
		values = { 
			{text = "Nothing(default)",help = "", key = 1, }, 
			{text = "Multiply units health by players in team",help = "", key = 2, }, 
			{text = "Multiply units number by players in team",help = "", key = 3, }, 
		}, 
	},
	
};